kind: Service
apiVersion: v1
metadata:
  name: kafka-rest-proxy
spec:
  type: ClusterIP
  ports:
  - name: port-8082
    port: 8082
    targetPort: 8082
    protocol: TCP 
  selector:
    app: kafka-rest
