apiVersion: v1
kind: Service
metadata:
  name: kaf1
spec:
  type: ClusterIP
  ports:
    - name: port-9092
      port: 9092
      protocol: TCP
  selector:
    app: kafka1
---
apiVersion: v1
kind: Service
metadata:
  name: kaf2
spec:
  type: ClusterIP
  ports:
    - name: port-9093
      port: 9093
      protocol: TCP
  selector:
    app: kafka2
