kind: Service
apiVersion: v1
metadata:
  name: zookeeper1
spec:
  type: ClusterIP
  ports:
  - name: port-2181
    port: 2181
    protocol: TCP 
  - name: port-2888
    port: 2888
    protocol: TCP 
  - name: port-3888
    port: 3888
    protocol: TCP 
    targetPort: 32181
  selector:
    app: zookeeper1

---
kind: Service
apiVersion: v1
metadata:
  name: zookeeper2
spec:
  type: ClusterIP
  ports:
  - name: port-2181
    port: 2181
    targetPort: 2181
    protocol: TCP 
  - name: port-2888
    port: 2888
    protocol: TCP 
    targetPort: 2888
  - name: port-3888
    port: 3888
    targetPort: 3888
    protocol: TCP 
  - name: port-32181
    port: 32181
    targetPort: 32181
    protocol: TCP
  selector:
    app: zookeeper2

